local U = require("better_gh.util")

---@param P table
---@param O table
---@return table<string, vim.api.keyset.highlight>
return function(P, O)
  local bg = O.transparent_background and P.none or P.base
  local bg_nc = O.transparent_background and P.none or P.base

  local float_bg = O.transparent_background and P.none or P.float_bg
  local inactive_bg = O.transparent_background and P.none or P.mantle
  local cursor_band = O.transparent_background and P.none or P.line

  local h = {
    ColorColumn = { bg = U.blend(P.err, P.base, 0.12) },
    Conceal = { fg = P.subtle },
    CurSearch = { fg = P.base, bg = P.warn },
    Cursor = { fg = P.base, bg = P.accent },
    lCursor = { link = "Cursor" },
    CursorIM = { link = "Cursor" },
    CursorColumn = { bg = cursor_band },
    CursorLine = { bg = cursor_band },
    CursorLineNr = { fg = P.line_nr_cur, bold = true },
    Directory = { fg = P.accent },
    DiffAdd = { bg = P.diff_add },
    DiffChange = { bg = P.diff_chg },
    DiffDelete = { bg = P.diff_del },
    DiffText = { bg = P.diff_text },
    EndOfBuffer = { fg = bg == P.none and P.subtle or U.blend(P.subtle, bg, 0.35), bg = bg },
    ErrorMsg = { fg = P.err, bold = true },
    WinSeparator = { fg = P.border, bg = bg },
    Folded = { fg = P.subtle, bg = P.mantle },
    FoldColumn = { fg = P.line_nr, bg = bg },
    SignColumn = { fg = P.line_nr, bg = bg },
    IncSearch = { fg = P.base, bg = P.keyword },
    -- bg NONE: gutter inherits window Normal (fixes fzf-lua preview vs explicit editor bg seam).
    LineNr = { fg = P.line_nr, bg = P.none },
    MatchParen = { fg = P.accent, bold = true },
    ModeMsg = { fg = P.fg },
    MsgArea = { fg = P.fg, bg = bg },
    MoreMsg = { fg = P.accent },
    NonText = { fg = P.whitespace },
    Normal = { fg = P.fg, bg = bg },
    NormalNC = { fg = P.fg, bg = bg_nc },
    NormalFloat = { fg = P.fg, bg = float_bg },
    FloatBorder = { fg = P.float_border_hi, bg = float_bg },
    FloatTitle = { fg = P.fg, bg = float_bg, bold = true },
    Pmenu = { fg = P.fg, bg = P.pmenu_bg },
    PmenuSel = { fg = P.fg, bg = P.pmenu_sel },
    PmenuSbar = { bg = P.mantle },
    PmenuThumb = { bg = P.subtle },
    Question = { fg = P.accent },
    QuickFixLine = { bg = P.surface_hover },
    Search = { fg = P.base, bg = P.warn },
    SpecialKey = { fg = P.subtle },
    SpellBad = { undercurl = true, sp = P.err },
    SpellCap = { undercurl = true, sp = P.warn },
    SpellLocal = { undercurl = true, sp = P.hint },
    SpellRare = { undercurl = true, sp = P.info },
    StatusLine = { fg = P.fg, bg = bg },
    StatusLineNC = { fg = P.muted, bg = P.mantle },
    TabLine = { fg = P.muted, bg = P.mantle },
    TabLineFill = { bg = P.mantle },
    TabLineSel = { fg = P.fg, bg = bg },
    Title = { fg = P.title, bold = true },
    Visual = { bg = P.sel },
    VisualNOS = { link = "Visual" },
    WarningMsg = { fg = P.warn },
    Whitespace = { fg = P.whitespace },
    WildMenu = { fg = P.fg, bg = P.pmenu_sel },

    Comment = { fg = P.comment, italic = true },
    Constant = { fg = P.const },
    String = { fg = P.string },
    Character = { fg = P.keyword },
    Number = { fg = P.number },
    Boolean = { fg = P.bool },
    Float = { fg = P.number },
    Identifier = { fg = P.fg },
    Function = { fg = P.func },
    Statement = { fg = P.keyword },
    Conditional = { fg = P.keyword },
    Repeat = { fg = P.keyword },
    Label = { fg = P.keyword },
    Operator = { fg = P.keyword },
    Keyword = { fg = P.keyword },
    Exception = { fg = P.keyword },
    PreProc = { fg = P.keyword },
    Include = { fg = P.keyword },
    Define = { fg = P.keyword },
    Macro = { fg = P.keyword },
    PreCondit = { fg = P.keyword },
    Type = { fg = P.type },
    StorageClass = { fg = P.storage },
    Structure = { fg = P.type },
    Typedef = { fg = P.type },
    Special = { fg = P.builtin },
    SpecialChar = { fg = P.escape },
    Tag = { fg = P.tag },
    Delimiter = { fg = P.punct },
    SpecialComment = { fg = P.subtle, italic = true },
    Debug = { fg = P.warn },

    Underlined = { underline = true },
    Ignore = { fg = P.subtle },
    Error = { fg = P.err },
    Todo = { fg = P.warn, bold = true },

    Added = { fg = P.git_add },
    Changed = { fg = P.git_change },
    Removed = { fg = P.git_delete },
    diffAdded = { link = "DiffAdd" },
    diffRemoved = { link = "DiffDelete" },
    diffChanged = { link = "DiffChange" },

    WinBar = { fg = P.muted, bg = bg },
    WinBarNC = { fg = P.subtle, bg = inactive_bg },

    DiagnosticError = { fg = P.err },
    DiagnosticWarn = { fg = P.warn },
    DiagnosticInfo = { fg = P.info },
    DiagnosticHint = { fg = P.hint },
    DiagnosticOk = { fg = P.ok },
    DiagnosticUnderlineError = { undercurl = true, sp = P.err },
    DiagnosticUnderlineWarn = { undercurl = true, sp = P.warn },
    DiagnosticUnderlineInfo = { undercurl = true, sp = P.info },
    DiagnosticUnderlineHint = { undercurl = true, sp = P.hint },
    DiagnosticFloatingError = { fg = P.err, bg = float_bg },
    DiagnosticFloatingWarn = { fg = P.warn, bg = float_bg },
    DiagnosticFloatingInfo = { fg = P.info, bg = float_bg },
    DiagnosticFloatingHint = { fg = P.hint, bg = float_bg },
    DiagnosticSignError = { fg = P.err, bg = bg },
    DiagnosticSignWarn = { fg = P.warn, bg = bg },
    DiagnosticSignInfo = { fg = P.info, bg = bg },
    DiagnosticSignHint = { fg = P.hint, bg = bg },

    -- Tint against editor chroma so transparent_background (Normal bg NONE) still works.
    DiagnosticVirtualTextError = { fg = P.err, bg = U.blend(P.err, P.base, 0.14) },
    DiagnosticVirtualTextWarn = { fg = P.warn, bg = U.blend(P.warn, P.base, 0.12) },
    DiagnosticVirtualTextInfo = { fg = P.info, bg = U.blend(P.info, P.base, 0.10) },
    DiagnosticVirtualTextHint = { fg = P.hint, bg = U.blend(P.hint, P.base, 0.10) },
    DiagnosticVirtualTextOk = { fg = P.ok, bg = U.blend(P.ok, P.base, 0.10) },

    LspReferenceText = { bg = P.sel_highlight },
    LspReferenceRead = { bg = P.sel_highlight },
    LspReferenceWrite = { bg = P.sel_highlight },
    LspSignatureActiveParameter = { underline = true, sp = P.accent },

    -- Blink.nvim / nvim-cmp fallbacks when not using nvim_cmp groups
    CmpItemAbbr = { fg = P.fg },
    CmpItemAbbrMatch = { fg = P.accent, bold = true },
    CmpItemAbbrDeprecated = { fg = P.subtle, strikethrough = true },
    CmpItemKind = { fg = P.builtin },
    CmpItemMenu = { fg = P.muted },
    CmpItemKindSnippet = { fg = P.field },
    CmpItemKindKeyword = { fg = P.keyword },
    CmpItemKindText = { fg = P.fg },
    CmpItemKindMethod = { fg = P.method },
    CmpItemKindConstructor = { fg = P.method },
    CmpItemKindFunction = { fg = P.func },
    CmpItemKindField = { fg = P.fg },
    CmpItemKindVariable = { fg = P.fg },
    CmpItemKindClass = { fg = P.type },
    CmpItemKindInterface = { fg = P.type },
    CmpItemKindModule = { fg = P.builtin },
    CmpItemKindProperty = { fg = P.fg },
    CmpItemKindUnit = { fg = P.number },
    CmpItemKindValue = { fg = P.const },
    CmpItemKindEnum = { fg = P.type },
    CmpItemKindOperator = { fg = P.keyword },
    CmpItemKindEnumMember = { fg = P.const },
    CmpItemKindConstant = { fg = P.const },
    CmpItemKindStruct = { fg = P.type },
    CmpItemKindEvent = { fg = P.warn },
    CmpItemKindFile = { fg = P.fg },
    CmpItemKindFolder = { fg = P.accent },
    CmpItemKindColor = { fg = P.warn },
    CmpItemKindReference = { fg = P.builtin },
    CmpItemKindDefault = { fg = P.fg },

    PmenuKind = { fg = P.builtin },
    PmenuExtra = { fg = P.muted },

    markdownCode = { fg = P.string },
    markdownLinkText = { fg = P.link, underline = true },

    jsonKeyword = { fg = P.property },
    yamlMappingKey = { fg = P.property },
  }

  return h
end
