---@param P table
---@param O table
---@return table<string, vim.api.keyset.highlight>
return function(P, _O)
  local h = {
    -- Treesitter (@-prefixed captures)
    ["@annotation"] = { fg = P.builtin },
    ["@attribute"] = { fg = P.builtin },
    ["@boolean"] = { fg = P.bool },
    ["@character"] = { fg = P.string },
    ["@character.special"] = { fg = P.escape },
    ["@comment"] = { link = "Comment" },
    ["@comment.documentation"] = { fg = P.comment, italic = true },
    ["@comment.error"] = { fg = P.err },
    ["@comment.warning"] = { fg = P.warn },
    ["@comment.note"] = { fg = P.hint },
    ["@comment.todo"] = { fg = P.warn, bold = true },

    ["@constant"] = { fg = P.const },
    ["@constant.builtin"] = { fg = P.builtin },
    ["@constant.macro"] = { fg = P.keyword },

    ["@constructor"] = { fg = P.method },
    ["@debug"] = { fg = P.warn },
    ["@define"] = { fg = P.keyword },
    ["@error"] = { fg = P.err },

    ["@function"] = { fg = P.func },
    ["@function.builtin"] = { fg = P.builtin },
    ["@function.call"] = { fg = P.func },
    ["@function.macro"] = { fg = P.keyword },

    ["@include"] = { fg = P.keyword },
    ["@keyword"] = { fg = P.keyword },
    ["@keyword.coroutine"] = { fg = P.keyword },
    ["@keyword.function"] = { fg = P.keyword },
    ["@keyword.operator"] = { fg = P.keyword },
    ["@keyword.import"] = { fg = P.keyword },
    ["@keyword.return"] = { fg = P.keyword },
    ["@keyword.exception"] = { fg = P.keyword },
    ["@keyword.type"] = { fg = P.keyword },
    ["@keyword.repeat"] = { fg = P.keyword },
    ["@keyword.storage"] = { fg = P.storage },
    ["@keyword.directive"] = { fg = P.keyword },
    ["@keyword.directive.define"] = { fg = P.keyword },

    ["@label"] = { fg = P.accent },

    ["@method"] = { fg = P.method },
    ["@method.call"] = { fg = P.method },

    ["@namespace"] = { fg = P.type },

    ["@none"] = {},
    ["@number"] = { fg = P.number },
    ["@number.float"] = { fg = P.number },

    ["@operator"] = { fg = P.fg },

    ["@parameter"] = { fg = P.param },
    ["@parameter.reference"] = { fg = P.param },

    ["@preproc"] = { fg = P.keyword },

    -- TS/JS/React (semantic hl): properties read as fg.default in VS Code; TextMate-only
    -- grammars use blue for meta.property-name — we match what TS/React shows in practice.
    ["@property"] = { fg = P.fg },
    ["@punctuation.bracket"] = { fg = P.punct },
    ["@punctuation.delimiter"] = { fg = P.punct },
    ["@punctuation.special"] = { fg = P.keyword },

    ["@string"] = { fg = P.string },
    ["@string.documentation"] = { fg = P.comment },
    ["@string.escape"] = { fg = P.escape, bold = true },
    ["@string.regexp"] = { fg = P.regex },
    ["@string.special"] = { fg = P.escape },

    ["@symbol"] = { fg = P.fg },

    ["@tag"] = { fg = P.tag },
    -- JSX/HTML attrs: theme maps meta.tag.attributes → fg.default (not orange).
    ["@tag.attribute"] = { fg = P.fg },
    ["@tag.delimiter"] = { fg = P.punct },

    ["@text"] = { fg = P.fg },
    ["@text.danger"] = { fg = P.err },
    ["@text.diff.add"] = { fg = P.git_add },
    ["@text.diff.delete"] = { fg = P.git_delete },
    ["@text.emphasis"] = { italic = true },
    ["@text.environment"] = { fg = P.keyword },
    ["@text.environment.name"] = { fg = P.builtin },
    ["@text.literal"] = { fg = P.string },
    ["@text.math"] = { fg = P.func },
    ["@text.note"] = { fg = P.hint },
    ["@text.reference"] = { fg = P.link, underline = true },
    ["@text.strike"] = { strikethrough = true },
    ["@text.strong"] = { bold = true },
    ["@text.title"] = { fg = P.title, bold = true },
    ["@text.todo"] = { fg = P.warn, bold = true },
    ["@text.uri"] = { fg = P.link, underline = true },
    ["@text.warning"] = { fg = P.warn },

    ["@type"] = { fg = P.type },
    ["@type.builtin"] = { fg = P.builtin },
    ["@type.definition"] = { fg = P.type },
    ["@type.qualifier"] = { fg = P.keyword },

    -- Dominant vscode scope for locals is variable.other → fg.default.
    ["@variable"] = { fg = P.fg },
    ["@variable.builtin"] = { fg = P.builtin },
    -- meta.object.member → fg.default (member access, optional chaining, etc.).
    ["@variable.member"] = { fg = P.fg },
    ["@variable.parameter"] = { fg = P.param },

    -- Markdown / markup (extra captures used by some parsers)
    ["@markup.heading"] = { fg = P.title, bold = true },
    ["@markup.heading.1"] = { fg = P.title, bold = true },
    ["@markup.heading.2"] = { fg = P.title, bold = true },
    ["@markup.heading.3"] = { fg = P.title, bold = true },
    ["@markup.heading.4"] = { fg = P.title, bold = true },
    ["@markup.heading.5"] = { fg = P.title, bold = true },
    ["@markup.heading.6"] = { fg = P.title, bold = true },
    ["@markup.bold"] = { bold = true },
    ["@markup.italic"] = { italic = true },
    ["@markup.strikethrough"] = { strikethrough = true },
    ["@markup.underline"] = { underline = true },
    ["@markup.quote"] = { fg = P.tag, italic = true },
    ["@markup.math"] = { fg = P.func },
    ["@markup.environment"] = { fg = P.keyword },
    ["@markup.environment.name"] = { fg = P.builtin },
    ["@markup.link"] = { fg = P.link, underline = true },
    ["@markup.link.label"] = { fg = P.link },
    ["@markup.link.url"] = { fg = P.link, underline = true },
    ["@markup.raw"] = { fg = P.builtin },
    ["@markup.list"] = { fg = P.keyword },
    ["@markup.list.checked"] = { fg = P.git_add },
    ["@markup.list.unchecked"] = { fg = P.muted },

    -- Legacy aliases (nvim-treesitter sometimes links old names)
    TSAnnotation = { link = "@annotation" },
    TSAttribute = { link = "@attribute" },
    TSBoolean = { link = "@boolean" },
    TSCharacter = { link = "@character" },
    TSComment = { link = "@comment" },
    TSConstructor = { link = "@constructor" },
    TSConstant = { link = "@constant" },
    TSConstBuiltin = { link = "@constant.builtin" },
    TSConstMacro = { link = "@constant.macro" },
    TSError = { link = "@error" },
    TSException = { link = "@keyword.exception" },
    TSFloat = { link = "@number.float" },
    TSFunction = { link = "@function" },
    TSFuncBuiltin = { link = "@function.builtin" },
    TSFuncMacro = { link = "@function.macro" },
    TSInclude = { link = "@include" },
    TSKeyword = { link = "@keyword" },
    TSKeywordFunction = { link = "@keyword.function" },
    TSKeywordOperator = { link = "@keyword.operator" },
    TSKeywordReturn = { link = "@keyword.return" },
    TSLabel = { link = "@label" },
    TSMethod = { link = "@method" },
    TSNamespace = { link = "@namespace" },
    TSNone = { link = "@none" },
    TSNumber = { link = "@number" },
    TSOperator = { link = "@operator" },
    TSParameter = { link = "@parameter" },
    TSParameterReference = { link = "@parameter.reference" },
    TSProperty = { link = "@property" },
    TSPunctDelimiter = { link = "@punctuation.delimiter" },
    TSPunctBracket = { link = "@punctuation.bracket" },
    TSPunctSpecial = { link = "@punctuation.special" },
    TSRepeat = { link = "@keyword.repeat" },
    TSString = { link = "@string" },
    TSStringRegex = { link = "@string.regexp" },
    TSStringEscape = { link = "@string.escape" },
    TSStringSpecial = { link = "@string.special" },
    TSSymbol = { link = "@symbol" },
    TSTag = { link = "@tag" },
    TSTagAttribute = { link = "@tag.attribute" },
    TSTagDelimiter = { link = "@tag.delimiter" },
    TSText = { link = "@text" },
    TSStrong = { link = "@text.strong" },
    TSEmphasis = { link = "@text.emphasis" },
    TSUnderline = { link = "@markup.underline" },
    TSStrike = { link = "@markup.strikethrough" },
    TSTitle = { link = "@markup.heading" },
    TSLiteral = { link = "@text.literal" },
    TSURI = { link = "@text.uri" },
    TSMath = { link = "@markup.math" },
    TSTextReference = { link = "@text.reference" },
    TSEnvironment = { link = "@markup.environment" },
    TSEnvironmentName = { link = "@markup.environment.name" },
    TSNote = { link = "@text.note" },
    TSWarning = { link = "@text.warning" },
    TSDanger = { link = "@text.danger" },
    TSType = { link = "@type" },
    TSTypeBuiltin = { link = "@type.builtin" },
    TSVariable = { link = "@variable" },
    TSVariableBuiltin = { link = "@variable.builtin" },

    -- Semantic tokens (LSP) — broad defaults
    ["@lsp.type.namespace"] = { link = "@namespace" },
    ["@lsp.type.type"] = { link = "@type" },
    ["@lsp.type.class"] = { link = "@type" },
    ["@lsp.type.enum"] = { link = "@type" },
    ["@lsp.type.interface"] = { link = "@type" },
    ["@lsp.type.struct"] = { link = "@type" },
    ["@lsp.type.typeParameter"] = { link = "@type" },
    ["@lsp.type.parameter"] = { link = "@parameter" },
    ["@lsp.type.variable"] = { link = "@variable" },
    ["@lsp.type.property"] = { link = "@property" },
    ["@lsp.type.enumMember"] = { link = "@constant" },
    ["@lsp.type.function"] = { link = "@function" },
    ["@lsp.type.method"] = { link = "@method" },
    ["@lsp.type.keyword"] = { link = "@keyword" },
    ["@lsp.type.operator"] = { link = "@operator" },
    ["@lsp.type.macro"] = { link = "@function.macro" },
    ["@lsp.type.decorator"] = { link = "@function" },
    ["@lsp.type.comment"] = { link = "@comment" },
    ["@lsp.type.string"] = { link = "@string" },
    ["@lsp.type.number"] = { link = "@number" },
    ["@lsp.type.regexp"] = { link = "@string.regexp" },
    ["@lsp.type.boolean"] = { link = "@boolean" },

    ["@lsp.mod.abstract"] = { italic = true },
    ["@lsp.mod.async"] = { italic = true },
    ["@lsp.mod.declaration"] = { bold = true },
    ["@lsp.mod.defaultLibrary"] = { fg = P.builtin },
    ["@lsp.mod.definition"] = { bold = true },
    ["@lsp.mod.deprecated"] = { fg = P.subtle, strikethrough = true },
    ["@lsp.mod.documentation"] = { fg = P.comment },
    ["@lsp.mod.modification"] = { underline = true },
    ["@lsp.mod.readonly"] = { fg = P.const },

  }

  return h
end
